# ---- DEVELOPMENT BUILD ----
FROM node:22-alpine

WORKDIR /usr/src/app

# Install global dependencies
RUN npm install -g @nestjs/cli cross-env

# Install dependencies first
COPY package*.json ./
RUN npm install

# Copy the rest of your app
COPY . .

# Expose app port
EXPOSE 5000

# Default command for live reload
CMD ["npm", "run", "start:dev"]